### ISSUE TITLE
Add a new source. Write a source that can read a list of URLs and then would feed each of those URLs for processing.

### ISSUE THREAD

**Issue by schue** [filterbubbler/filterbubbler-web-ext#56]
Take a URL and that URLs content is a list of URLs.
File access in web extensions, can’t read files on a users computer
Editor in UI to paste URLs into it.
Sanitize, validate entry.

**Comment by biancadanforth** [comment]
The idea is that there is perhaps a `<textarea>` form field where the user can paste a list of URLs and the classifier can batch process them (i.e. classify all of them at once instead of the user having to navigate to each page individually).

We would want to ensure that what the user enters is a valid list of URLs and we would also need to sanitize the string to prevent any XSS (Cross-Site Scripting).

@schue How would this list get fed into the classifier? Could you give some pseudocode and more specifics?

**Comment by schue** [comment]
Check out GH-48 you can see that the current-page source now feeds the current page content to the classifier. I was imagining that we would read the list of URLs from a URL and feed them to the classifier one after another which would then fire the connected sink. It could also be a textarea but that would involve providing a way for sources and sinks to add their own UI elements to the recipe configuration (a worthy goal that should have its own issue).
